# Generated by Django 5.2 on 2025-05-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_alter_attributeoption_option_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('thumbnail', 'Thumbnail'), ('gallery', 'Gallery')], default='thumbnail', max_length=20),
        ),
    ]
